sudo: required
services:
  - docker

before_install:
  - docker build -t rabrahams/dockerkub -f Dockerfile.dev .

script:
  - docker run rabrahams/dockerkub npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerkub"
  env: "Dockerkub-env"
  bucket_name: "elasticbeanstalk-us-east-2-412011447019"
  bucket_path: "dockerkub"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
